### ISSUE TITLE
DUnitX causes Internal Compiler Error in XE3 Update 1

### ISSUE THREAD

**Issue by vincentparrett** [VSoftTechnologies/DUnitX#117]
[dcc32 Fatal Error] DUnitX.TestFramework.pas(871): F2084 Internal Error: G9413

It appears to be this bug 
http://qc.embarcadero.com/wc/qcmain.aspx?d=111979

I tried the work around, and it compiles, however then the TDUnitX class constructor does not get called.  The compiler bug was fixed in XE4.

**Comment by robsoft** [comment]
Hi Vincent, is there any kind of workaround I could do, to get this to work for the time being? I have an XE3 update 1 project that I'd really like to introduce DUnitX into, and I'm not going to be able to move it to XE7/8 for a few months yet. I appreciate XE3 is long since dead, but if there's any simple hack I could use to get it to work for the time being, that would be really helpful. Thank you!

**Comment by vincentparrett** [comment]
I tried but was not able to find a work around. Perhaps someone else might have a suggestion.

**Comment by robsoft** [comment]
Wow, thanks for the quick response! I appreciate it, if I come across anything in the meantime I will report back. Keep up the good work, it's really appreciated :-)

**Comment by fabriciocolombo** [comment]
@robsoft  I just send a pullrequest that workaround the problem. Can you try it, please?

**Comment by robsoft** [comment]
nice one Fabricio, I just made your suggested changes here manually in my local copy and it certainly seems to do the trick on a new project. Thank you!
