### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by henriquewerlang** [VSoftTechnologies/DUnitX#125]
When activated the "Emit runtime type information", a compilation error occurs for which has fields in classes that do not have the scope definition set.

PS: "Translation by Bing"

**Comment by vincentparrett** [comment]
Sorry, not sure what you mean. Post your question in your native language and perhaps another contributor might be able to help.

**Comment by henriquewerlang** [comment]
Se você ativar, no projeto a opção "Emit runtime type information", dá um erro na unit "DUnitX.Utils", na classe "TAttributeUtils", o erro de compilação "[dcc32 Error] DUnitX.Utils.pas(82): E2266 Only one of a set of overloaded methods can be published", por que as funções não tem a definição do escopo, tem que colocar lá o "public", ai para o erro.

**Comment by henriquewerlang** [comment]
Mandei um pull request com os ajustes.

**Comment by fabriciocolombo** [comment]
It was missing the visibility definition (default to published) to TAttributeUtils class, and with `Emit runtime type information` option activated the compilation fails with a `E2266: Only one of a set of overloaded methods can be published` error because of `FindAttribute` overloaded function.

Fixed in #132

**Comment by vincentparrett** [comment]
Thanks, Merged #132
