### ISSUE TITLE
Implement a Gui Runner with Delphi XE2

### ISSUE THREAD

**Issue by JayJayParis** [VSoftTechnologies/DUnitX#155]
Hello,

I tried to make a project with a GUI with Delphi XE2.
I followed this issue to make it: [(https://github.com/VSoftTechnologies/DUnitX/issues/154)]

But i can't compile the project. I have the following error : 
`F1026 File not found: 'System.Actions.dcu' (unit scope "System" indicates Win64, OSX32, Win32 only)`

I searched on the web and "System.Actions" appeared with Delphi XE3.

Is it possible to make a gui project with Delphi WE2 ?

Jay

**Comment by rpottsoh** [comment]
Try viewing the gui runner in your xe2 IDE.  The gui was stored having last been open in a later version of Delphi.   The gui runner works in XE and I have it working in XE5.  I don't know how much testing has occurred on XE versions in between.  It ought to work.  Sorry not very helpful. 

Sent from my android device.

-----Original Message-----

**Comment by JayJayParis** [comment]
I think that the framework is not currently compatible with XE2:
 - I can't compile the project example "DUnitXExamples_XE2". At the compilation, i have an error in the fonction "ConvStr2DynArray" (unit DUnitX.Utils) : E2003 Undeclared identifier : "TypeData"
 - When i try to open the form "DUnitX.Loggers.GUI.VCL", Delphi doesn't know the property "Zoom" of the component rchText (TRichEdit)

**Comment by rmcginty** [comment]
It is compatible with XE2, but as @rpottsoh mentioned, XE2 is not one of the versions that we've tested with.  I use XE and 10.1 Berlin while others use 2010 and XE7 for sure.  Not sure what other versions have been tried, but XE2 is not one I've seen mentioned.  

As for the issue, XE2 must've not moved the ActionList components to namespaced units, or they were named something else.  I'll look into it and make modifications for the next PR.  In the meantime, if I figure it out, I'll post the solution here.  Opening the form may or may not fix the issue without you manually messing with the uses clause - the form designer goes crazy with the way the uses is done with conditionals.  As for the Zoom property, that is because someone opened it in a higher version of Delphi before committing.  Any "property" errors can safely be ignored.

The ConvStr2DynArray is a known issue that I opened in #152.  I had to conditionalize out all of that stuff to compile in XE, but I've not done a PR yet.  I updated the issue to reflect that it doesn't work in XE2 either.

**Comment by rpottsoh** [comment]
XE5 works just have to disregard error message for zoom feature.

Ryan

Sent from my android device.

-----Original Message-----

**Comment by rmcginty** [comment]
Noted - thanks for the info!

**Comment by rmcginty** [comment]
@vincentparrett I think you can close this if no one objects.

**Comment by Nashev** [comment]
On the page https://github.com/VSoftTechnologies/DUnitX in Readme it's feel like any own GUI is deprecated here,  in favor of using TestInsight (https://bitbucket.org/sglienke/testinsight/wiki/Home)
