### ISSUE TITLE
When BRCC32 throws `Fatal error Illegal macro definition in command line or defines page.` in a DUnitX project

### ISSUE THREAD

**Issue by jpluimers** [VSoftTechnologies/DUnitX#158]
I had a [Fatal error Illegal macro definition in command line or defines page.](https://www.google.com/search?q="Fatal+error+Illegal+macro+definition+in+command+line+or+defines+page.") thrown by [BRCC32.exe](https://www.google.com/search?q=BRCC32.exe) in one of my Delphi projects.

As [cgrc.exe could build the .rc file](http://www.progtown.com/post37220712.html#p37220712) [[source](http://www.sql.ru/forum/1112611/msbuild-opciya-dlya-rc-faylov) in Russian; [WayBack](http://web.archive.org/web/20160908092623/http://www.sql.ru/forum/1112611/msbuild-opciya-dlya-rc-faylov)], I reproduced it from the console with an Empty.rc file that has no content. That way I could rule out file content: now it had to be command-line arguments which is a different cause than any of the [search results](https://www.google.com/search?q="Fatal+error+Illegal+macro+definition+in+command+line+or+defines+page.") I found before.

My project was based on one of the [DUnitX test projects](https://github.com/VSoftTechnologies/DUnitX/blob/master/Tests/DUnitXTest_XE8.dproj). It ran in [Delphi XE8](https://wiert.me/2016/02/13/bldn-december-2015-xe7xe8-update-subscription-update-got-released-20160211-with-backported-10-seattle-fixes/), but the Delphi version doesn't matter as BRCC32 hasn't been updated since 1999.

Further below are the failure/success examples; this went wrong:

- DUnitX uses the `DUNITX-DEBUG` define to enable debugging of DUnitX itself [in DUnitX.inc](https://github.com/VSoftTechnologies/DUnitX/blob/master/DUnitX.inc#L254) which also supports the `DUNITXDEBUG` define [in the same area](https://github.com/VSoftTechnologies/DUnitX/blob/master/DUnitX.inc#L255).
- Delphi will translate a .RC file in a project into a BRCC32.exe call adding the project conditional defines and search paths
- BRCC32.exe doesn't like hyphens in conditional defines throwing a non-descriptive error `Fatal error Illegal macro definition in command line or defines page.`

So either removing `DUNITX-DEBUG` or changing it into `DUNITXDEBUG` solves the problem. Hence my pull-request.

This fails:

```
C:\Temp>"c:\program files (x86)\embarcadero\studio\16.0\bin\brcc32.exe" -dDUNITX-DEBUG;DEBUG;TESTINSIGHT -iC:\Users\Public\Documents\Embarcadero\Studio\16.0\SelectiveDebugging\Win32;"c:\program files (x86)\embarcadero\studio\16.0\lib\Win32\release";C:\Users\jeroenp\Documents\Embarcadero\Studio\16.0\Imports;"c:\program files (x86)\embarcadero\studio\16.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\16.0\Dcp;"c:\program files (x86)\embarcadero\studio\16.0\include";"C:\Program Files (x86)\FastReports\LibD22";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE8\Win32";"C:\Program Files (x86)\FastReport 5 VCL Enterprise\LIBD22" Empty.rc -foEmpty.res
Borland Resource Compiler Version 5.40
Copyright (c) 1990, 1999 Inprise Corporation. All rights reserved.

Fatal error Illegal macro definition in command line or defines page.
```

This works:

```
C:\Temp>"c:\program files (x86)\embarcadero\studio\16.0\bin\brcc32.exe" -d;DEBUG;TESTINSIGHT -iC:\Users\Public\Documents\Embarcadero\Studio\16.0\SelectiveDebugging\Win32;"c:\program files (x86)\embarcadero\studio\16.0\lib\Win32\release";C:\Users\jeroenp\Documents\Embarcadero\Studio\16.0\Imports;"c:\program files (x86)\embarcadero\studio\16.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\16.0\Dcp;"c:\program files (x86)\embarcadero\studio\16.0\include";"C:\Program Files (x86)\FastReports\LibD22";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE8\Win32";"C:\Program Files (x86)\FastReport 5 VCL Enterprise\LIBD22" Empty.rc -foEmpty.res
Borland Resource Compiler Version 5.40
Copyright (c) 1990, 1999 Inprise Corporation. All rights reserved.
```

--jeroen

**Comment by rmcginty** [comment]
Jeez - glad you figured out what the issue was given that cryptic message.  I added the non-hyphenated one because I have stuff wrapped in IFDEF DEBUG and the hyphenated, at least in XE, would cause the DEBUG blocks to be compiled too, so something was definitely odd about using hyphens in conditionals across the board.  My next PR actually defines at least one conditional that uses underscore.  Can you see if it crashes the resource compile in your setup?  I know other people use them seemingly more often than hyphens, but am curious if this is more related to defines in projects and such rather than those strictly used in code (such DELPHI_XE, IS_64BIT, etc).

**Comment by jpluimers** [comment]
@rmcginty thanks. Basically it's just eliminating causes in a structured way (:

Just checked: `DUNITX_DEBUG` as a conditional define works fine with BRCC32.exe.

I think the cause of the BRCC32.exe error is that defines need to be an "identifier" for the resource compiler. Just like in the Object Pascal language, underscores are fine in identifiers, but hyphens are not.

The Object Pascal apparently has other rules for conditional defines than for regular identifiers, though looking at your comment in https://github.com/VSoftTechnologies/DUnitX/blob/master/DUnitX.inc#L249 those rules aren't handled consistently in the Delphi tool-chain.

**Comment by rmcginty** [comment]
Yeah, I guess I should read my own comments :)  I forgot that I tested the underscore while working on that!  

I do believe that it has something to do with being a "passed" or "project defined" conditional instead of code only.  I think the general rule of thumb should be if it is required to be on a command line and/or defined in the project file, it is probably best to avoid special chars altogether.  I'm going to change my current working source to reflect that...

Thanks for testing it in your setup and reporting back!  Always helpful while it is fresh on the brain to know what combinations work where and what do not.

**Comment by vincentparrett** [comment]
DUNITX-DEBUG is really only intended for DUnitX developers, when it's not defined we turn of debug info for dunitx, stops users having to step through DUnitX when debugging their tests.
