### ISSUE TITLE
Test Cases pass incorrect parameters with a space in the parameters section of the attribute

### ISSUE THREAD

**Issue by DaveMartel** [VSoftTechnologies/DUnitX#191]
Not able to test in Tokyo yet, but in Berlin when I use a test case something like this

```
    [Test]
    //DUnitX/Delphi BUG?   Shows expected as "True", should be "False".
    //  Space seems to freak it out
    [TestCase('TestTop_NoChg2', '3,0, False')]
    [TestCase('TestTop_NoChg3', '3,0,False')]   
    procedure Change_XX_Sets_DirtyFlag(WhichItem: Integer; Incr: Integer; ExpectedFlag: boolean);


```
TestTop_NoChg3 works fine and False is passed correctly to "ExpectedFlag"

In TestTop_NoChg2 the test fails because ExpectedFlag gets set to True.

I have traced in to the DUnitX code in the debugger, and it looks like in 
DUnitX.Attributes.pas 

```
constructor TestCaseAttribute.Create()...
..

  lValues := SplitString(AValues,ASeparator);
  l := Length(lValues);
  SetLength(FCaseInfo.Values,l);

..

```
returns 
['3,'0,' False']

Then 
TValue.From<string>(' False')  returns true

Now I know this is an issue I can work around it, but it does seem like rather a weakness. It is rather hard to debug unless you know to look for it and could lead to false positives, or worse still "false negatives" on tests, letting them pass when they really need to fail.

Thanks

**Comment by rpottsoh** [comment]
@DaveMartel I have come across this issue with 10.2 Tokyo.
```pascal
[testcase('foo','12, 13')]
procedure myTest(const aExpected: integer; const aInput: integer);
```
`aInput` will actually equal `13` as an integer.  However

```pascal
[testcase('bar','12, input')]
procedure myOtherTest(const aExpected: integer; const aInput: string);
```
This time `aInput` equals `' input'` instead of `'input'`.

I wouldn't call this a huge deal now that I have come across it.  As long as there is now space following the `,` there is no problem.

Would it be acceptable to trim all spaces that follow the character that separates values?

I think this is allowed:
```pascal
[testcase('my test','12, 13',', ')] 
```
The last part designates the separation string.  I am not sure if more than one character is allowed.  I have not used it before, just opting for the default `,`.

**Comment by DaveMartel** [comment]
Again using Berlin, rather than Tokyo... but I suspect the version is not the issue....

I have tried using a multi character separator, but it does not work. Looking in the DUnitX source it would appear to use the separator you suggest as 2 possible separators, comma and space. Hence it would split strings. So no go.

I agree it is not the biggest issue. I just thought I would raise it since I saw it. 

The biggest issue for me was the fact that nothing fails and nothing is flagged, you just get an unexpected result. Since unexpected results are the sort of thing we use unit testing to avoid, it seems to me that it might be something that would merit fixing.

**Comment by jkour** [comment]
When using the parameters in the tests, always always always use Trim() unless spaces are meaningful in your design. 

This will save you lots of trouble.

Although it is a bit inconvenient the way DUnitX handles it, I wouldn't consider it huge problem. But it would be good to handle the spaces

**Comment by vincentparrett** [comment]
The problem with us trimming spaces, is what then happens if you actually want to pass spaces? At the moment the code that fills the params is pretty looseygoosey (in TDUnitXTestCase.Create ) and doesn't really do anything to ensure correct types etc. I'm happy to look at suggests, feel free to submit a pull request, unfortunately I don't have time to look at this right now, working 7 days a week dealing with existing workload (ie paying the bills)!

**Comment by jkour** [comment]
@vincentparrett Exactly and that's why I said unless spaces are meaningful in the design.

My suggestion was to the user to use trim in the procedure as they see fit. In my view, nothing has to change regarding the spaces as they can be managed in the code as already said. So I don't thing this is a real issue.

Alternatively, and if this is a needed functionality, we could have a kind of global option (like opIgnoreSpaces = false) which can be changed whenever needed. Or, even a third parameter in the TestCase attribute to specify this behaviour.

Having said that I think it's better all of us to work on some overload attributes to accept other types than string.

**Comment by DaveMartel** [comment]
My original post was not say it was right or wrong. I said in my post that it was something you can work around (and yes, using trim is what I was thinking).

I really only raised it so people were aware of it. It is not mentioned anywhere I have found. I googled around and found no other reports of this. So I hoped by pointing out the issue that perhaps people might mot get caught out.

So an option might be nice, but just happy if it adds a little to the global knowledge.

**Comment by Nashev** [comment]
Add one more optional argument 'ATrimSpaces: Boolean = False' to DUnitX.Attributes.TestCaseAttribute.Create and all will be correct and predictable.
